apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: samplepython2-ojh7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-tgornals-tenant/compromisedapp/samplepython2-ojh7@sha256:dfb1c116f6c96bd54de3d399a78aa52557202b514fd79b2180800eb3c86bcb03
        name: my-python
        resources: {}
status: {}
