apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: samplepython2-ojh7
  namespace: rhn-support-tgornals-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-tgornals-tenant/compromisedapp/samplepython2-ojh7@sha256:4d2ec63a68708cf37259d88f0ce4a6c0cfc63d6ff8b75b35ea57de4c059a2497
        name: my-python
        resources: {}
status: {}
