apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: samplepython2-ojh7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: samplepython2-ojh7
    app.kubernetes.io/part-of: compromisedapp
  name: samplepython2-ojh771oq
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: samplepython2-ojh7
    weight: null
status: {}
