apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: samplepython2-ojh7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: samplepython2-ojh7
    app.kubernetes.io/part-of: compromisedapp
  name: samplepython2-ojh7
  namespace: rhn-support-tgornals-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: samplepython2-ojh7
status:
  loadBalancer: {}
